name: Deploy to GitHub Pages

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Copy files
        run: |
          release_v = ${{ github.ref_name }}
          mkdir -p "./_LVsite/${release_v}"
          cp -r ./en "./_LVsite/${release_v}/"
          cp -r ./ru "./_LVsite/${release_v}/"
          cp ./index.html "./_LVsite/${release_v}/"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_LVsite 
          keep_files: true 
